syntax on
" 4 space tab
set tabstop=4
" use 4 space tab for > and <
set shiftwidth=4
" use shiftwidth for beginning of the line
set smarttab
" use spaces when tab is pressed
set expandtab
" treat spaces as tabstop, so can delete easily
set softtabstop=4
" start properly tabbed in when pressing enter
set autoindent
" Tell vim to remember certain things when we exit
"  '10  :  marks will be remembered for up to 10 previously edited files
"  "100 :  will save up to 100 lines for each register
"  :20  :  up to 20 lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files
set viminfo='10,\"100,:20,%,n~/.viminfo
" restore cursor to previous position
function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END
set backspace=indent,eol,start